other:
  - rqt --perspective-file /catkin_ws/src/ros_biomech/acquisition_state_machines/acquisition_of_raw_data/Acquisition_minimal.perspective
  #- rosrun rqt_runtime_monitor rqt_runtime_monitor
  #- rosrun rqt_reconfigure rqt_reconfigure  
  - roslaunch republisher republisher_insoles.launch --wait
##"rosrun rqt_graph rqt_graph"


main_nodes:
  - roslaunch test_moticon_insoles show_urdf_everything.launch use_gui:=false
#"roslaunch ximu3_ros ximu_lower.launch do_calibration:=true parent_frame_id:=subject_heading wait_to_start:=true"
  - roslaunch ximu3_ros ximu_lower.launch do_calibration:=true wait_to_start:=true
  - roslaunch osrt_ros t46.launch bypass_heading_computation:=false heading_debug:=0 visualise:=false orientation_server_type:=tf
  - roslaunch osrt_ros vis_ik.launch
  - roslaunch osrt_ros id_async_filtered2.launch get_second_label:=false left_foot_tf_name:=left_cop_filtered right_foot_tf_name:=right_cop_filtered max_buffer_length:=1000 ik_delay:=0.26 --wait 
  - roslaunch moticon_insoles read_sdk.launch tf_prefix:=ik/ --wait
