main_nodes:
  - roslaunch test_moticon_insoles show_urdf_everything.launch use_gui:=false
#"roslaunch ximu3_ros ximu_lower.launch do_calibration:=true parent_frame_id:=subject_heading wait_to_start:=true"
  - roslaunch ximu3_ros ximu_lower.launch do_calibration:=true wait_to_start:=true dummy_publisher:=true
  - roslaunch osrt_ros t42.launch run_as_service:=true parent_frame:=map
##"roslaunch osrt_ros ik_lowerbody_inverted_pelvis.launch"
  - roslaunch osrt_ros t46.launch bypass_heading_computation:=true heading_debug:=0 visualise:=false orientation_server_type:=tf
###"rosrun rqt_robot_monitor rqt_robot_monitor" ## in the future, this is nice to organize things but it looks complicated
  - rosrun rqt_runtime_monitor rqt_runtime_monitor
  - rosrun rqt_reconfigure rqt_reconfigure
  - roslaunch osrt_ros vis_ik.launch
##"rosrun rqt_graph rqt_graph"
