imu_viz:
  - rviz -d /catkin_ws/src/ros_biomech/ximu3_ros/ximu_line.rviz 
  - roslaunch ximu3_ros upright.launch

imu_nodes:

  - roslaunch ximu3_ros lower_torso.launch do_calibration:=true wait_to_start:=true
  - roslaunch ximu3_ros lower_pelvis.launch do_calibration:=true wait_to_start:=true
  - roslaunch ximu3_ros lower_femur_r.launch do_calibration:=true wait_to_start:=true
  - roslaunch ximu3_ros lower_femur_l.launch do_calibration:=true wait_to_start:=true
  - roslaunch ximu3_ros lower_tibia_r.launch do_calibration:=true wait_to_start:=true
  - roslaunch ximu3_ros lower_tibia_l.launch do_calibration:=true wait_to_start:=true
  - roslaunch ximu3_ros lower_talus_r.launch do_calibration:=true wait_to_start:=true
  - roslaunch ximu3_ros lower_talus_l.launch do_calibration:=true wait_to_start:=true
